workspace(name = "test_workspace")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

MAVEN_REPOSITORY_RULES_VERSION = "2.0.0-alpha-5"

MAVEN_REPOSITORY_RULES_CHECKSUM = "fde80cafa02a2c034cc8086c158f500e7b6ceb16d251273a6cc82f1c0723e0e8"

# Create a bazel workspace to represent the maven universe.
http_archive(
    name = "maven_repository_rules",
    sha256 = MAVEN_REPOSITORY_RULES_CHECKSUM,
    strip_prefix = "bazel_maven_repository-%s" % MAVEN_REPOSITORY_RULES_VERSION,
    type = "zip",
    urls = ["https://github.com/square/bazel_maven_repository/archive/%s.zip" % MAVEN_REPOSITORY_RULES_VERSION],
)
#local_repository(
#    name = "maven_repository_rules",
#    path = "..",
#)

load("@maven_repository_rules//maven:maven.bzl", "maven_repository_specification")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

KOTLIN_VERSION = "1.4.32"

KOTLINC_ROOT = "https://github.com/JetBrains/kotlin/releases/download"

KOTLINC_URL = "{root}/v{v}/kotlin-compiler-{v}.zip".format(
    root = KOTLINC_ROOT,
    v = KOTLIN_VERSION,
)

KOTLINC_SHA = "dfef23bb86bd5f36166d4ec1267c8de53b3827c446d54e82322c6b6daad3594c"

KOTLIN_RULES_VERSION = "1.5.0-beta-3"

KOTLIN_RULES_SHA = "58edd86f0f3c5b959c54e656b8e7eb0b0becabd412465c37a2078693c2571f7f"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = KOTLIN_RULES_SHA,
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % KOTLIN_RULES_VERSION],
)
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories(compiler_release = {
    "urls": [KOTLINC_URL],
    "sha256": KOTLINC_SHA,
})

kt_register_toolchains()

maven_repository_specification(
    name = "maven",

    # The artifact spec list.
    artifacts = {
        "com.github.ajalt.clikt:clikt-jvm:3.2.0": {"insecure": True},
        "com.google.code.findbugs:jsr305:3.0.2": {"insecure": True},
        "com.google.errorprone:error_prone_annotations:2.3.1": {"insecure": True},
        "com.google.guava:guava:27.1-jre": {
            "insecure": True,
            "exclude": [
                "com.google.guava:failureaccess",
                "com.google.guava:listenablefuture",
            ],
        },
        "com.google.j2objc:j2objc-annotations:1.1": {"insecure": True},
        "com.google.truth:truth:1.0": {
            "insecure": True,
            "testonly": True,
            "exclude": ["com.google.auto.value:auto-value-annotations"],
        },
        "com.googlecode.java-diff-utils:diffutils:1.3.0": {"insecure": True},
        "com.squareup.moshi:moshi:1.9.2": {"insecure": True},
        "com.squareup.moshi:moshi-kotlin:1.9.2": {"insecure": True},
        "com.squareup.okhttp3:okhttp:4.4.1": {"insecure": True},
        "com.squareup.okio:okio:2.4.3": {"insecure": True},
        "com.squareup.tools.build:maven-archeologist:0.0.8": {"insecure": True},
        "junit:junit:4.13": {
            "insecure": True,
            "testonly": True,
        },
        "org.apache.commons:commons-lang3:3.8.1": {"insecure": True},
        "org.apache.maven:maven-artifact:3.6.3": {"insecure": True},
        "org.apache.maven:maven-builder-support:3.6.3": {"insecure": True},
        "org.apache.maven:maven-model-builder:3.6.3": {
            "insecure": True,
            "exclude": [
                "javax.inject:javax.inject",
                "org.eclipse.sisu:org.eclipse.sisu.inject",
            ],
        },
        "org.apache.maven:maven-model:3.6.3": {"insecure": True},
        "org.checkerframework:checker-compat-qual:2.5.5": {"insecure": True},
        "org.checkerframework:checker-qual:2.5.2": {"insecure": True},
        "org.codehaus.mojo:animal-sniffer-annotations:1.17": {"insecure": True},
        "org.codehaus.plexus:plexus-interpolation:1.25": {"insecure": True},
        "org.codehaus.plexus:plexus-utils:3.2.1": {"insecure": True},
        "org.hamcrest:hamcrest-core:1.3": {"insecure": True},
        "org.jetbrains.kotlin:kotlin-reflect:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-stdlib-common:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-stdlib:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-stdlib-jdk7:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5": {"insecure": True},
        "org.jetbrains:annotations:13.0": {"insecure": True},
        "org.pantsbuild:jarjar:1.7.2": {
            "insecure": True,
            "exclude": [
                "org.apache.ant:ant",
                "org.apache.maven:maven-plugin-api",
            ],
        },
        "org.ow2.asm:asm:7.1": {"insecure": True},
        "org.ow2.asm:asm-analysis:7.1": {"insecure": True},
        "org.ow2.asm:asm-commons:7.1": {"insecure": True},
        "org.ow2.asm:asm-tree:7.1": {"insecure": True},
    },
    repository_urls = {
        "central": "https://repo1.maven.org/maven2",
        "google": "https://maven.google.com",
    },
)

android_sdk_repository(
    name = "androidsdk",
    api_level = 30,
    build_tools_version = "30.0.1",
)
