# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - release*
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        workspace:
          - .
          - test/test_workspace
          - kramer
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.8 }
      - name: Mount caches
        uses: actions/cache@v2
        with:
          path: |
            "/home/runner/.cache/bazel"
            "/home/runner/.m2/repository"
          key: caches-${{ runner.os }}
      - name: Setup bazelisk for Bazel builds
        uses: holvonix-open/setup-bazelisk@v0.6.1
      - name: Build ${{ matrix.workspace }}
        run: (cd ${{ matrix.workspace }} && bazel build //...)
      - name: Test ${{ matrix.workspace }}
        run: (cd ${{ matrix.workspace }} && bazel test //...)
