# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - release*
  pull_request:
    branches: [ master ]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          "/home/runner/.cache/bazel"
          "/home/runner/.m2/repository"
        key: caches-${{ runner.os }}
    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-darwin-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod a+x "${GITHUB_WORKSPACE}/bin/bazel"
        echo "::set-env name=BAZELISK_GITHUB_TOKEN::${{ secrets.GITHUB_TOKEN }}"
    - name: Test All
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...
    - name: Test Kramer
      run: |
        (cd kramer && "${GITHUB_WORKSPACE}/bin/bazel" test //...)
    - name: Build the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" build //...)
    - name: Test the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" test //...)

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          "/home/runner/.cache/bazel"
          "/home/runner/.m2/repository"
        key: caches-${{ runner.os }}
    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod a+x "${GITHUB_WORKSPACE}/bin/bazel"
        echo "::set-env name=BAZELISK_GITHUB_TOKEN::${{ secrets.GITHUB_TOKEN }}"
    - name: Test All
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...
    - name: Test Kramer
      run: |
        (cd kramer && "${GITHUB_WORKSPACE}/bin/bazel" test //...)
    - name: Build the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" build //...)
    - name: Test the Test Workspace
      run: |
        (cd test/test_workspace && "${GITHUB_WORKSPACE}/bin/bazel" test //...)
